spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.houduan.entity

server:
  port: 8081
